version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: davlo-web
    restart: unless-stopped
    ports:
      - "8000:3000"
    networks:
      - caddy
    labels:
      caddy: davlo.io
      caddy.reverse_proxy: "{{upstreams 3000}}"
      caddy.encode: gzip
      caddy.header.Strict-Transport-Security: "max-age=31536000; includeSubDomains; preload"
      caddy.header.X-Content-Type-Options: "nosniff"
      caddy.header.X-Frame-Options: "DENY"
      caddy.header.X-XSS-Protection: "1; mode=block"
      caddy.header.Referrer-Policy: "strict-origin-when-cross-origin"

networks:
  caddy:
    external: true
